name: content-management-frontend
static_sites:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/content-management-frontend
  build_command: npm run build
  output_dir: dist
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  routes:
  - path: /
  - path: /assets
